### ISSUE TITLE
The local env credentials are not loaded

### ISSUE THREAD

**Issue by anbarasanv** [toughyear/gaac#1]
Hi Team,

I was trying to execute the nextjs code base on the local.

Though I have added the required credentials on the `.env.local` - while clicking on the connect button the auth redirect happens via the default link given in the code and after the redirect I guess rest of the actions are happening via the **gaac vercel app** rather than the **local code base**.

![image](https://github.com/toughyear/gaac/assets/33603902/b914549a-48ee-4b24-bd92-de30a1361ef1)

Is there a detail documentation to run in the local or Is there any code tweak required?

**Comment by toughyear** [comment]
If you don't want to use the default `GaaC` app that I've created, you can create a new one on GitHub and get the `client_id` and use that. For local dev, you can use the `redirect_uri` to point to your local URL.
